### ISSUE TITLE
Error while installing in cocoapods

### ISSUE THREAD

**Issue by scinfu** [realm/realm-cocoa#1022]
Any idea ?

 Xcode 6.0.1
cocoapods 0.34.2

``` ruby
Installing Realm (0.86.3)
[!] /bin/bash
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...

Downloading dependency: core 0.84.0

Archive:  /tmp/core_bin/core-0.84.0.zip
replace core/include/tightdb/alloc.hpp? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL

(assuming [N]one)

mv: rename /tmp/core_bin/core-0.84.0 to ./core-0.84.0: No such file or directory' 
```

**Comment by yishuiliunian** [comment]
can't find  the core_bin directory  in /tmp, and i got this problem too

**Comment by erikhermans3** [comment]
Deleting temporary directory ( rm -rf /tmp/core_bin ) worked for me.

**Comment by xujianfeng123** [comment]
YES,Deleting temporary directory ( rm -rf /tmp/core_bin ) worked for me.👌

**Comment by Kaelzzs** [comment]
clean. And then "pod install" use terminal.

**Comment by ashokds** [comment]
Getting similar error:

I have empty project based on xcode8 beta 6. Using cocoapods 1.0.1.

` pod install
Analyzing dependencies
Downloading dependencies
Installing Realm (1.0.2)
[!] /bin/bash -c
set -e
sh build.sh cocoapods-setup`


Podfile: 

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Realm_101' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Realm_101
  pod 'RealmSwift'

  target 'Realm_101Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Realm_101UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

**Comment by ashokds** [comment]
Any idea @jpsim @scinfu ?

**Comment by jpsim** [comment]
Xcode 8 beta 6 came out a few days ago. The last official release of Realm Swift was on July 13th. You'll need to target `master` to have the latest Swift 3 changes in Realm Swift:

```ruby
target 'Realm_101' do
# Comment this line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

# Pods for Realm_101
pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', :submodules => true
pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', :submodules => true

target 'Realm_101Tests' do
inherit! :search_paths
# Pods for testing
end

target 'Realm_101UITests' do
inherit! :search_paths
# Pods for testing
end

end
```

**Comment by ashokds** [comment]
Hi @jpsim,
I tried both 'Realm' & 'RealmSwift' using master.

```
use_frameworks!

target 'Realm_101' do

  # Pods for Realm_101
  #pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', :submodules => true
  pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', :submodules => true

  target 'Realm_101Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Realm_101UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

getting same error

```
pod install
Analyzing dependencies
Pre-downloading: `Realm` from `https://github.com/realm/realm-cocoa.git`, branch `master`, submodules `true`
[!] /bin/bash -c
set -e
sh build.sh cocoapods-setup
```

**Comment by jpsim** [comment]
@ashokds what you posted are normal logs. Where's the error?

**Comment by ashokds** [comment]
Unlike @scinfu's log, in my case there is nothing after following:
```
[!] /bin/bash -c
set -e
sh build.sh cocoapods-setup
```

Do I need to find logs somewhere else? Other pods are working fine, except 'Realm', 'RealmSwift' or 'SugarRecord' (has dependency on Realm).

pod install --verbose

```
pod install --verbose
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-Realm_101`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-Realm_101Tests`:
  (``)
  Using `ARCHS` setting to build architectures of target
  `Pods-Realm_101UITests`: (``)

Fetching external sources
-> Pre-downloading: `Realm` from `https://github.com/realm/realm-cocoa.git`, branch `master`, submodules `true`
 > Git download
 > Git download
     $ /usr/local/bin/git clone https://github.com/realm/realm-cocoa.git
     /var/folders/m3/rrsgdbg16sx4gn19qpy497nrhg335x/T/d20160818-68761-v3payo
     --template= --single-branch --depth 1 --branch master
     Cloning into '/var/folders/m3/rrsgdbg16sx4gn19qpy497nrhg335x/T/d20160818-68761-v3payo'...
     $ /usr/local/bin/git submodule update --init --recursive
     Submodule 'Realm/ObjectStore' (https://github.com/realm/realm-object-store.git) registered for path 'Realm/ObjectStore'
     Cloning into '/private/var/folders/m3/rrsgdbg16sx4gn19qpy497nrhg335x/T/d20160818-68761-v3payo/Realm/ObjectStore'...
     Submodule path 'Realm/ObjectStore': checked out '6a47d44fa8562e1c998eea57ce8a01eea7d11031'
     Submodule 'external/catch' (https://github.com/philsquared/Catch) registered for path 'Realm/ObjectStore/external/catch'
     Submodule 'external/pegtl' (https://github.com/ColinH/PEGTL) registered for path 'Realm/ObjectStore/external/pegtl'
     Cloning into '/private/var/folders/m3/rrsgdbg16sx4gn19qpy497nrhg335x/T/d20160818-68761-v3payo/Realm/ObjectStore/external/catch'...
     Cloning into '/private/var/folders/m3/rrsgdbg16sx4gn19qpy497nrhg335x/T/d20160818-68761-v3payo/Realm/ObjectStore/external/pegtl'...
     Submodule path 'Realm/ObjectStore/external/catch': checked out 'f294c9847272b1b92c5119a6f711e57113b5f231'
     Submodule path 'Realm/ObjectStore/external/pegtl': checked out '3c4128a7e7e1288eb746418ea60c41477358f26a'
 > Running prepare command
   $ /bin/bash -c  set -e sh build.sh cocoapods-setup
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup



/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/executable.rb:69:in `execute_command'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/executable.rb:27:in `block in executable'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/pod_source_preparer.rb:66:in `block (2 levels) in run_prepare_command'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/pod_source_preparer.rb:60:in `chdir'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/pod_source_preparer.rb:60:in `block in run_prepare_command'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/pod_source_preparer.rb:59:in `run_prepare_command'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/pod_source_preparer.rb:37:in `prepare!'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader/cache.rb:201:in `copy_and_clean'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader/cache.rb:158:in `block (2 levels) in uncached_pod'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader/cache.rb:156:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader/cache.rb:156:in `block in uncached_pod'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader/cache.rb:180:in `in_tmpdir'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader/cache.rb:152:in `uncached_pod'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader.rb:39:in `download'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/external_sources/abstract_external_source.rb:114:in `block in pre_download'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:84:in `titled_section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/external_sources/abstract_external_source.rb:112:in `pre_download'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/external_sources/downloader_source.rb:13:in `fetch'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:479:in `fetch_external_source'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:455:in `block (2 levels) in fetch_external_sources'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:454:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:454:in `block in fetch_external_sources'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:453:in `fetch_external_sources'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:73:in `analyze'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:227:in `analyze'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:151:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:150:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:114:in `install!'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/command/install.rb:37:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by jpsim** [comment]
@ashokds `cocoapods-setup` downloads Realm's core binaries from the web. If you're killing the process before it has a chance to complete the download and local setup, then the installation process isn't getting the chance to complete.

Can you make sure that you're connected to the Internet while you're installing Realm?

**Comment by ashokds** [comment]
@jpsim Yes. I am connected to internet. I have another project that depends on 8 other podspecs and all of the environment is same (shared: machine, wifi-connection, ruby/cocoapods/etc). Only issue could be that I am using xcode8beta6 for a test project to explore Realm.

**Comment by jpsim** [comment]
Alright, I think we've stretched the limit of discussing this on an issue from 2014, please file a new issue taking care to fill out the template and sharing as much information as possible about your situation and how we can reproduce the faulty behavior you're seeing, and we'll take a closer look.
