### ISSUE TITLE
Realm/RLMPlatform.h file not found in ver.0.90.1

### ISSUE THREAD

**Issue by 3ign0n** [realm/realm-cocoa#1400]
Should it be included in Realm.podspec public_header_files?

**Comment by ldiqual** [comment]
Ok, now it's getting a bit weird: 3 versions in a row that the Podspec is broken even though it was allegedly fixed every single time.

 - "fix" for 0.89.0: https://github.com/realm/realm-cocoa/pull/1358
 - "fix" for 0.90.0: https://github.com/realm/realm-cocoa/pull/1393
 - fix? for 0.90.1: https://github.com/realm/realm-cocoa/commit/11da29b925ed2789e9a42f6670d49a06d1484610

I could be totally wrong, but it seems that [testing the podspec locally](https://github.com/realm/realm-cocoa/pull/1393#issuecomment-71098205) would have detected the issue before each release. I definitely appreciate the reactivity of engineers on this project and I'd love if I could make sure that the next Podspec works.

Would you mind giving me steps to test it locally? Here's what I did:
 - Cloned realm into the `realm-cocoa/` directory
 - Applied this patch: https://github.com/realm/realm-cocoa/commit/11da29b925ed2789e9a42f6670d49a06d1484610
 - Linted the pod: `$ pod --verbose spec lint realm-cocoa/Realm.podspec`.

This is what I get:
```
[ldiqual@Loiss-MacBook-Air realm-cocoa]$ pod --verbose spec lint Realm.podspec 

    Realm (0.90.1) - Analyzing on iOS 6.0 platform.
  Preparing

Analyzing dependencies

Inspecting targets to integrate

Fetching external sources
-> Fetching podspec for `Realm` from `/Users/ldiqual/tests/Project/realm-cocoa/Realm.podspec`
sh: build.sh: No such file or directory

Resolving dependencies of 
sh: build.sh: No such file or directory
Starting resolution (2015-01-22 21:56:56 -0800)
Creating possibility state for Realm (from `/Users/ldiqual/tests/Project/realm-cocoa/Realm.podspec`) (1 remaining)
  Attempting to activate Realm
  Activated Realm at Realm
  Requiring nested dependencies (Realm/Headers (= ))
Finished resolution (1 steps) (Took 0.009556 seconds) (2015-01-22 21:56:56 -0800)
Unactivated: Realm/Headers
Activated: Realm

### Stack

   CocoaPods : 0.36.0.beta.1
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.1 (14B25)
       Xcode : 6.1 (6A1052d)
         Git : git version 2.2.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ badcbc610fef245fd1673c30ca8f19c8154d9c76

### Plugins

cocoapods-plugins : 0.4.0
cocoapods-trunk   : 0.3.1
cocoapods-try     : 0.4.3

### Error

ArgumentError - Illformed requirement `"= "`
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.0.beta.1/lib/cocoapods-core/requirement.rb:61:in `parse'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.0.beta.1/lib/cocoapods-core/vendor/requirement.rb:108:in `block in initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.0.beta.1/lib/cocoapods-core/vendor/requirement.rb:108:in `map!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.0.beta.1/lib/cocoapods-core/vendor/requirement.rb:108:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/resolver.rb:106:in `new'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/resolver.rb:106:in `search_for'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/resolver.rb:210:in `block in sort_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/resolver.rb:204:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/resolver.rb:204:in `sort_by'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/resolver.rb:204:in `sort_dependencies'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.2.0/lib/molinillo/resolution.rb:123:in `block (2 levels) in <class:Resolution>'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.2.0/lib/molinillo/resolution.rb:386:in `push_state_for_requirements'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.2.0/lib/molinillo/resolution.rb:378:in `require_nested_dependencies_for'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.2.0/lib/molinillo/resolution.rb:366:in `activate_spec'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.2.0/lib/molinillo/resolution.rb:343:in `attempt_to_activate_new_spec'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.2.0/lib/molinillo/resolution.rb:310:in `attempt_to_activate'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.2.0/lib/molinillo/resolution.rb:139:in `process_topmost_state'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.2.0/lib/molinillo/resolution.rb:68:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.2.0/lib/molinillo/resolver.rb:40:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/resolver.rb:55:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer/analyzer.rb:424:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer/analyzer.rb:422:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer/analyzer.rb:58:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer.rb:186:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer.rb:108:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer.rb:107:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer.rb:90:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/validator.rb:309:in `install_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/validator.rb:214:in `block in perform_extensive_analysis'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/validator.rb:210:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/validator.rb:210:in `perform_extensive_analysis'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/validator.rb:73:in `validate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/command/spec.rb:100:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/command/spec.rb:92:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/command/spec.rb:92:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.0/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/command.rb:45:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.1/bin/pod:43:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

Same thing happen if I link my podfile to a local Podspec with https://github.com/realm/realm-cocoa/blob/11da29b925ed2789e9a42f6670d49a06d1484610/Realm.podspec inside.

**Comment by segiddins** [comment]
I have a pull request that will fix linting in CocoaPods.

**Comment by ldiqual** [comment]
@segiddins That's super promising! Would you mind linking to it? I couldn't find it in the list of open PRs.

**Comment by segiddins** [comment]
https://github.com/CocoaPods/CocoaPods/pull/3067

-Samuel E. Giddins

On Jan 22, 2015, at 11:42 PM, Loïs Di Qual <notifications@github.com> wrote:

@segiddins That's super promising! Would you mind linking to it? I couldn't find it in the list of open PRs.

**Comment by denadai2** [comment]
same here
