### ISSUE TITLE
core is not a symlink. Deleting... Downloading dependency: core 0.89.6

### ISSUE THREAD

**Issue by fewspider** [realm/realm-cocoa#2312]
when I use `pod install`,I get some info like this.
My pod version is `0.38.2`.
```
Installing Realm (0.93.2)
[!] /bin/bash -c
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: core 0.89.6
```

**Comment by segiddins** [comment]
Can you please share your Podfile, or try running `pod update --verbose` and sharing the output of that? Thanks!

**Comment by fewspider** [comment]
cc @segiddins ,thanks :)
```
Update all pods
  Preparing

Updating local specs repositories

Updating spec repo `master`
  $ /usr/bin/git pull --ff-only
  From https://github.com/CocoaPods/Specs
     8214c2b..0cef7bb  master     -> origin/master
  Updating 8214c2b..0cef7bb
  Fast-forward
   Specs/EstimoteSDK/3.3.3/EstimoteSDK.podspec.json   | 35 ++++++++++++++++++++++
   Specs/TAKAlertUtil/0.2.1/TAKAlertUtil.podspec.json | 28 +++++++++++++++++
   2 files changed, 63 insertions(+)
   create mode 100644 Specs/EstimoteSDK/3.3.3/EstimoteSDK.podspec.json
   create mode 100644 Specs/TAKAlertUtil/0.2.1/TAKAlertUtil.podspec.json

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-Twicrow`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-TwicrowTests`: (``)

Finding Podfile changes
  - Alamofire
  - Dollar
  - OAuthSwift
  - RealmSwift

Resolving dependencies of `Podfile`

Comparing resolved specification to the sandbox manifest
  A Realm
  A RealmSwift
  M Dollar
  - Alamofire
  - OAuthSwift

Downloading dependencies

-> Using Alamofire (1.3.0)

-> Installing Dollar (3.0.3)
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/ankurp/Dollar.swift.git /var/folders/k3/3_s3q64n71s9qxkf3859g1x00000gn/T/d20150729-43410-1xq1c7r --single-branch --depth 1 --branch 3.0.3
     Cloning into '/var/folders/k3/3_s3q64n71s9qxkf3859g1x00000gn/T/d20150729-43410-1xq1c7r'...
     error: RPC failed; result=56, HTTP code = 200
     fatal: The remote end hung up unexpectedly
     fatal: early EOF
     fatal: unpack-objects failed

[!] Error installing Dollar
[!] /usr/bin/git clone https://github.com/ankurp/Dollar.swift.git /var/folders/k3/3_s3q64n71s9qxkf3859g1x00000gn/T/d20150729-43410-1xq1c7r --single-branch --depth 1 --branch 3.0.3

Cloning into '/var/folders/k3/3_s3q64n71s9qxkf3859g1x00000gn/T/d20150729-43410-1xq1c7r'...
error: RPC failed; result=56, HTTP code = 200
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: unpack-objects failed


/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/downloader.rb:130:in `rescue in execute_command'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/downloader.rb:128:in `execute_command'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-downloader-0.9.1/lib/cocoapods-downloader/base.rb:152:in `block in executable'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-downloader-0.9.1/lib/cocoapods-downloader/git.rb:65:in `block in clone'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/downloader.rb:161:in `block in ui_sub_action'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/downloader.rb:160:in `ui_sub_action'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-downloader-0.9.1/lib/cocoapods-downloader/git.rb:63:in `clone'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-downloader-0.9.1/lib/cocoapods-downloader/git.rb:29:in `download!'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-downloader-0.9.1/lib/cocoapods-downloader/base.rb:80:in `block in download'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/downloader.rb:145:in `block in ui_action'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/downloader.rb:144:in `ui_action'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-downloader-0.9.1/lib/cocoapods-downloader/base.rb:78:in `download'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/downloader.rb:110:in `download_source'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/downloader.rb:65:in `download_request'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/downloader/cache.rb:170:in `download'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/downloader/cache.rb:153:in `block in uncached_pod'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/downloader/cache.rb:180:in `call'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/downloader/cache.rb:180:in `in_tmpdir'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/downloader/cache.rb:152:in `uncached_pod'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/downloader.rb:34:in `download'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/installer/pod_source_installer.rb:103:in `download_source'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/installer/pod_source_installer.rb:53:in `install!'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:328:in `install_source_of_pod'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:303:in `block (2 levels) in install_pod_sources'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:80:in `titled_section'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:302:in `block in install_pod_sources'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:294:in `each'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:294:in `install_pod_sources'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:143:in `block in download_dependencies'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:141:in `download_dependencies'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:105:in `install!'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:156:in `run'
/Users/fewspider/.rvm/gems/ruby-2.2.1/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/Users/fewspider/.rvm/gems/ruby-2.2.1/bin/pod:23:in `load'
/Users/fewspider/.rvm/gems/ruby-2.2.1/bin/pod:23:in `<main>'
```

**Comment by fewspider** [comment]
cc @segiddins ,thanks :)
```
Update all pods
  Preparing

Updating local specs repositories

Updating spec repo `master`
  $ /usr/bin/git pull --ff-only
  From https://github.com/CocoaPods/Specs
     0cef7bb..f67d77e  master     -> origin/master
  Updating 0cef7bb..f67d77e
  Fast-forward
   .../0.4.4/SwiftAddressBook.podspec.json            | 26 ++++++++++++++++++++++
   1 file changed, 26 insertions(+)
   create mode 100644 Specs/SwiftAddressBook/0.4.4/SwiftAddressBook.podspec.json

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-Twicrow`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-TwicrowTests`: (``)

Finding Podfile changes
  - Alamofire
  - Dollar
  - OAuthSwift
  - RealmSwift

Resolving dependencies of `Podfile`

Comparing resolved specification to the sandbox manifest
  A Realm
  A RealmSwift
  M Dollar
  - Alamofire
  - OAuthSwift

Downloading dependencies

-> Using Alamofire (1.3.0)

-> Installing Dollar (3.0.3)
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/ankurp/Dollar.swift.git /var/folders/k3/3_s3q64n71s9qxkf3859g1x00000gn/T/d20150729-43758-dnqnfn --single-branch --depth 1 --branch 3.0.3
     Cloning into '/var/folders/k3/3_s3q64n71s9qxkf3859g1x00000gn/T/d20150729-43758-dnqnfn'...
     Note: checking out 'b3a84ec27e1833453843b19afde38d131bf78c9c'.

     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by performing another checkout.

     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -b with the checkout command again. Example:

       git checkout -b new_branch_name

  > Copying Dollar from `/Users/fewspider/Library/Caches/CocoaPods/Pods/Release/Dollar/3.0.3-ae37f` to `Pods/Dollar`

-> Using OAuthSwift (0.3.6)

-> Installing Realm (0.93.2)
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/realm/realm-cocoa.git /var/folders/k3/3_s3q64n71s9qxkf3859g1x00000gn/T/d20150729-43758-1e600c5 --single-branch --depth 1 --branch v0.93.2
     Cloning into '/var/folders/k3/3_s3q64n71s9qxkf3859g1x00000gn/T/d20150729-43758-1e600c5'...
     Note: checking out 'b51bbf47f508b7815a26c824cd0039824493ea07'.

     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by performing another checkout.

     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -b with the checkout command again. Example:

       git checkout -b new_branch_name

 > Running prepare command
   $ /bin/bash -c  set -e sh build.sh cocoapods-setup
   core is not a symlink. Deleting...
   Downloading dependency: core 0.89.6
[!] /bin/bash -c
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: core 0.89.6


/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/executable.rb:70:in `execute_command'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/executable.rb:27:in `block in executable'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/installer/pod_source_preparer.rb:64:in `block (2 levels) in run_prepare_command'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/installer/pod_source_preparer.rb:60:in `chdir'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/installer/pod_source_preparer.rb:60:in `block in run_prepare_command'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/installer/pod_source_preparer.rb:59:in `run_prepare_command'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/installer/pod_source_preparer.rb:37:in `prepare!'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/downloader/cache.rb:201:in `copy_and_clean'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/downloader/cache.rb:158:in `block (2 levels) in uncached_pod'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/downloader/cache.rb:156:in `each'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/downloader/cache.rb:156:in `block in uncached_pod'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/downloader/cache.rb:180:in `call'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/downloader/cache.rb:180:in `in_tmpdir'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/downloader/cache.rb:152:in `uncached_pod'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/downloader.rb:34:in `download'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/installer/pod_source_installer.rb:103:in `download_source'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/installer/pod_source_installer.rb:53:in `install!'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:328:in `install_source_of_pod'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:303:in `block (2 levels) in install_pod_sources'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:80:in `titled_section'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:302:in `block in install_pod_sources'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:294:in `each'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:294:in `install_pod_sources'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:143:in `block in download_dependencies'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:141:in `download_dependencies'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:105:in `install!'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:156:in `run'
/Users/fewspider/.rvm/gems/ruby-2.2.1/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Users/fewspider/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/Users/fewspider/.rvm/gems/ruby-2.2.1/bin/pod:23:in `load'
/Users/fewspider/.rvm/gems/ruby-2.2.1/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
That's really odd, @fewspider, since I can't reproduce this at all...

**Comment by fewspider** [comment]
@segiddins  It seems like a xcode cache problem or internet work problem.When I try to `Menu > Product > Clean` and retry install again, It is working. Anyway thanks for this awesome and powerful stuff. This issue can be closed now.

**Comment by segiddins** [comment]
Glad to hear you got things working!

**Comment by fewspider** [comment]
@segiddins 😁

**Comment by erikhermans3** [comment]
If cleaning cache does not work, please try to delete temporary download folder ( rm -rf /tmp/core_bin ).

**Comment by gstrekkie** [comment]
I ran into this problem today and came to find out that little snitch was blocking the connection to realm so perhaps you are experiencing a similar issue
