### ISSUE TITLE
EXC_BAD_ACCESS RLMRealm notification listener on lots of inserts

### ISSUE THREAD

**Issue by asjesset** [realm/realm-cocoa#4238]
Running Realm 2.0.2 .

I am getting an EXC_BAD_ACCESS sometimes during a massive save process (syncing a new email account).

There is a notification block active on a RLMResults that shows some of the content.

Here's the stacktrace:

```
RLMRealm notification listener (19)#0   0x00006280000dd0a0 in 0x6280000dd0a0 ()
#1  0x000000010972187e in realm::Array::get(unsigned long) const [inlined] at /Users/realm/workspace/create_github_release_cocoa/realm-cocoa/core/include/realm/array.hpp:1613
#2  0x0000000109721864 in realm::ArrayInteger::get(unsigned long) const [inlined] at /Users/realm/workspace/create_github_release_cocoa/realm-cocoa/core/include/realm/array_integer.hpp:200
#3  0x0000000109721864 in realm::SequentialGetter<realm::Column<long long> >::get_next(unsigned long) [inlined] at /Users/realm/workspace/create_github_release_cocoa/realm-cocoa/core/include/realm/impl/sequential_getter.hpp:89
#4  0x000000010972180c in void realm::Columns<long long>::evaluate_internal<realm::Column<long long> >(unsigned long, realm::ValueBase&) at /Users/realm/workspace/create_github_release_cocoa/realm-cocoa/core/include/realm/query_expression.hpp:2467
#5  0x000000010971d848 in realm::Compare<realm::Equal, long long, realm::Subexpr, realm::Subexpr>::find_first(unsigned long, unsigned long) const at /Users/realm/workspace/create_github_release_cocoa/realm-cocoa/core/include/realm/query_expression.hpp:3056
#6  0x00000001099880e4 in realm::ParentNode::find_first(unsigned long, unsigned long) ()
#7  0x000000010991d952 in realm::OrNode::find_first_local(unsigned long, unsigned long) ()
#8  0x000000010993e368 in bool realm::ColumnNodeBase::match_callback<(realm::Action)5, realm::Column<long long> >(long long) ()
#9  0x00000001099508f8 in bool realm::Array::compare_equality<true, (realm::Action)7, 2ul, std::__1::__bind<std::__1::__mem_fn<bool (realm::ColumnNodeBase::*)(long long)>, realm::IntegerNodeBase<realm::Column<long long> >*, std::__1::placeholders::__ph<1>&> >(long long, unsigned long, unsigned long, unsigned long, realm::QueryState<long long>*, std::__1::__bind<std::__1::__mem_fn<bool (realm::ColumnNodeBase::*)(long long)>, realm::IntegerNodeBase<realm::Column<long long> >*, std::__1::placeholders::__ph<1>&>) const ()
#10 0x0000000109950377 in bool realm::Array::find_optimized<realm::Equal, (realm::Action)7, 2ul, std::__1::__bind<std::__1::__mem_fn<bool (realm::ColumnNodeBase::*)(long long)>, realm::IntegerNodeBase<realm::Column<long long> >*, std::__1::placeholders::__ph<1>&> >(long long, unsigned long, unsigned long, unsigned long, realm::QueryState<long long>*, std::__1::__bind<std::__1::__mem_fn<bool (realm::ColumnNodeBase::*)(long long)>, realm::IntegerNodeBase<realm::Column<long long> >*, std::__1::placeholders::__ph<1>&>, bool, bool) const ()
#11 0x000000010994c841 in bool realm::Array::find<realm::Equal, (realm::Action)7, std::__1::__bind<std::__1::__mem_fn<bool (realm::ColumnNodeBase::*)(long long)>, realm::IntegerNodeBase<realm::Column<long long> >*, std::__1::placeholders::__ph<1>&> >(long long, unsigned long, unsigned long, unsigned long, realm::QueryState<long long>*, std::__1::__bind<std::__1::__mem_fn<bool (realm::ColumnNodeBase::*)(long long)>, realm::IntegerNodeBase<realm::Column<long long> >*, std::__1::placeholders::__ph<1>&>, bool, bool) const ()
#12 0x0000000109953c0c in bool realm::IntegerNodeBase<realm::Column<long long> >::find_callback_specialization<realm::Equal, (realm::Action)5, (realm::DataType)0, false>(unsigned long, unsigned long) ()
#13 0x000000010995407b in realm::IntegerNodeBase<realm::Column<long long> >::aggregate_local_impl(realm::QueryStateBase*, unsigned long, unsigned long, unsigned long, realm::SequentialGetterBase*, int) ()
#14 0x000000010994c314 in realm::IntegerNode<realm::Column<long long>, realm::Equal>::aggregate_local(realm::QueryStateBase*, unsigned long, unsigned long, unsigned long, realm::SequentialGetterBase*) ()
#15 0x000000010990e3fa in realm::Query::aggregate_internal(realm::Action, realm::DataType, bool, realm::ParentNode*, realm::QueryStateBase*, unsigned long, unsigned long, realm::SequentialGetterBase*) const ()
#16 0x000000010990f998 in realm::Query::find_all(realm::TableViewBase&, unsigned long, unsigned long, unsigned long) const ()
#17 0x000000010990eaf5 in realm::Query::find_all(unsigned long, unsigned long, unsigned long) ()
#18 0x00000001096da837 in realm::_impl::ResultsNotifier::run() at /Users/realm/workspace/create_github_release_cocoa/realm-cocoa/Realm/ObjectStore/src/impl/results_notifier.cpp:150
#19 0x00000001096ceddf in realm::_impl::RealmCoordinator::run_async_notifiers() at /Users/realm/workspace/create_github_release_cocoa/realm-cocoa/Realm/ObjectStore/src/impl/realm_coordinator.cpp:563
#20 0x00000001096ce7b4 in realm::_impl::RealmCoordinator::on_change() at /Users/realm/workspace/create_github_release_cocoa/realm-cocoa/Realm/ObjectStore/src/impl/realm_coordinator.cpp:378
#21 0x00000001096b9962 in realm::_impl::ExternalCommitHelper::listen() at /Users/realm/workspace/create_github_release_cocoa/realm-cocoa/Realm/ObjectStore/src/impl/apple/external_commit_helper.cpp:214
#22 0x00000001096ba41e in realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0::operator()() const [inlined] at /Users/realm/workspace/create_github_release_cocoa/realm-cocoa/Realm/ObjectStore/src/impl/apple/external_commit_helper.cpp:159
#23 0x00000001096ba419 in std::__1::__invoke<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0>(decltype(std::__1::forward<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0>(fp)(std::__1::forward<>(fp0))), realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0&&) [inlined] at /Applications/Xcode-8.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__functional_base:416
#24 0x00000001096ba410 in _ZNSt3__112__async_funcIZN5realm5_impl20ExternalCommitHelperC1ERNS2_16RealmCoordinatorEE3$_0JEE9__executeIJEEEvNS_15__tuple_indicesIJXspT_EEEE [inlined] at /Applications/Xcode-8.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/future:2348
#25 0x00000001096ba410 in std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0>::operator()() at /Applications/Xcode-8.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/future:2341
#26 0x00000001096ba3aa in std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >::__execute() at /Applications/Xcode-8.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/future:1031
#27 0x00000001096ba553 in std::__1::__invoke<void (std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >::*)(), std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >*, void>(decltype(*(std::__1::forward<std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >*>(fp0)).*fp(std::__1::forward<>(fp1))), void (std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >::*&&)(), std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >*&&) [inlined] at /Applications/Xcode-8.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__functional_base:383
#28 0x00000001096ba53a in _ZNSt3__116__thread_executeIMNS_19__async_assoc_stateIvNS_12__async_funcIZN5realm5_impl20ExternalCommitHelperC1ERNS4_16RealmCoordinatorEE3$_0JEEEEEFvvEJPSA_EJLm1EEEEvRNS_5tupleIJT_DpT0_EEENS_15__tuple_indicesIJXspT1_EEEE [inlined] at /Applications/Xcode-8.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/thread:347
#29 0x00000001096ba53a in std::__1::__thread_proxy<std::__1::tuple<void (std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >::*)(), std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >*> >(void*, void*) at /Applications/Xcode-8.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/thread:357
#30 0x0000000110390abb in _pthread_body ()
#31 0x0000000110390a07 in _pthread_start ()
#32 0x0000000110390231 in thread_start ()
```

I'm not sure what other information to provide. It does not happen all the time, even when supposedly the same data is inserted.

**Comment by jpsim** [comment]
I've cross-posted this in our core bug tracker to get our core people involved to investigate this further: realm/realm-core#2269

In the meantime, any further information you could provide us to help reproduce this on our end would be very useful.

**Comment by pauluhn** [comment]
I'm running into the same issue on RealmSwift 1.1.0
 
```
RLMRealm notification listener (13)#0	0x00006180002cc470 in 0x6180002cc470 ()
#1	0x0000000103f02e8a in realm::Array::get(unsigned long) const at /Users/pauluhn/Projects/cockpit-ios/Pods/Realm/include/core/realm/array.hpp:1582
#2	0x0000000103f03bc8 in realm::ArrayInteger::get(unsigned long) const at /Users/pauluhn/Projects/cockpit-ios/Pods/Realm/include/core/realm/array_integer.hpp:203
#3	0x00000001040370a4 in realm::SequentialGetter<realm::Column<long long> >::get_next(unsigned long) [inlined] at /Users/pauluhn/Projects/cockpit-ios/Pods/Realm/include/core/realm/impl/sequential_getter.hpp:83
#4	0x0000000104036f58 in void realm::Columns<long long>::evaluate_internal<realm::Column<long long> >(unsigned long, realm::ValueBase&) at /Users/pauluhn/Projects/cockpit-ios/Pods/Realm/include/core/realm/query_expression.hpp:2275
#5	0x000000010403522d in realm::Columns<long long>::evaluate(unsigned long, realm::ValueBase&) at /Users/pauluhn/Projects/cockpit-ios/Pods/Realm/include/core/realm/query_expression.hpp:2321
#6	0x0000000104028371 in realm::Compare<realm::Equal, long long, realm::Subexpr, realm::Subexpr>::find_first(unsigned long, unsigned long) const at /Users/pauluhn/Projects/cockpit-ios/Pods/Realm/include/core/realm/query_expression.hpp:2812
#7	0x00000001042f1150 in realm::ParentNode::find_first(unsigned long, unsigned long) ()
#8	0x000000010429d372 in realm::OrNode::find_first_local(unsigned long, unsigned long) ()
#9	0x00000001042f1400 in realm::ParentNode::aggregate_local(realm::QueryStateBase*, unsigned long, unsigned long, unsigned long, realm::SequentialGetterBase*) ()
#10	0x000000010428da9a in realm::Query::aggregate_internal(realm::Action, realm::DataType, bool, realm::ParentNode*, realm::QueryStateBase*, unsigned long, unsigned long, realm::SequentialGetterBase*) const ()
#11	0x000000010428ef17 in realm::Query::find_all(realm::TableViewBase&, unsigned long, unsigned long, unsigned long) const ()
#12	0x000000010428e195 in realm::Query::find_all(unsigned long, unsigned long, unsigned long) ()
#13	0x0000000103fadce7 in realm::_impl::ResultsNotifier::run() at /Users/pauluhn/Projects/cockpit-ios/Pods/Realm/Realm/ObjectStore/src/impl/results_notifier.cpp:147
#14	0x0000000103f795ac in realm::_impl::RealmCoordinator::run_async_notifiers() at /Users/pauluhn/Projects/cockpit-ios/Pods/Realm/Realm/ObjectStore/src/impl/realm_coordinator.cpp:491
#15	0x0000000103f77075 in realm::_impl::RealmCoordinator::on_change() at /Users/pauluhn/Projects/cockpit-ios/Pods/Realm/Realm/ObjectStore/src/impl/realm_coordinator.cpp:306
#16	0x0000000103f2320f in realm::_impl::ExternalCommitHelper::listen() at /Users/pauluhn/Projects/cockpit-ios/Pods/Realm/Realm/ObjectStore/src/impl/apple/external_commit_helper.cpp:214
#17	0x0000000103f284f7 in realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0::operator()() const at /Users/pauluhn/Projects/cockpit-ios/Pods/Realm/Realm/ObjectStore/src/impl/apple/external_commit_helper.cpp:159
#18	0x0000000103f284cd in std::__1::__invoke<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0>(decltype(std::__1::forward<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0>(fp)(std::__1::forward<>(fp0))), realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0&&) [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__functional_base:416
#19	0x0000000103f284bc in _ZNSt3__112__async_funcIZN5realm5_impl20ExternalCommitHelperC1ERNS2_16RealmCoordinatorEE3$_0JEE9__executeIJEEEvNS_15__tuple_indicesIJXspT_EEEE at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/future:2348
#20	0x0000000103f28485 in std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0>::operator()() at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/future:2341
#21	0x0000000103f283af in std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >::__execute() at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/future:1031
#22	0x0000000103f28e24 in std::__1::__invoke<void (std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >::*)(), std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >*, void>(decltype(*(std::__1::forward<std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >*>(fp0)).*fp(std::__1::forward<>(fp1))), void (std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >::*&&)(), std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >*&&) [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__functional_base:383
#23	0x0000000103f28da5 in _ZNSt3__116__thread_executeIMNS_19__async_assoc_stateIvNS_12__async_funcIZN5realm5_impl20ExternalCommitHelperC1ERNS4_16RealmCoordinatorEE3$_0JEEEEEFvvEJPSA_EJLm1EEEEvRNS_5tupleIJT_DpT0_EEENS_15__tuple_indicesIJXspT1_EEEE [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/thread:347
#24	0x0000000103f28d7d in std::__1::__thread_proxy<std::__1::tuple<void (std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >::*)(), std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >*> >(void*, void*) at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/thread:357
#25	0x0000000107cf3aab in _pthread_body ()
#26	0x0000000107cf39f7 in _pthread_start ()
#27	0x0000000107cf3221 in thread_start ()

```
<img width="1416" alt="screen shot 2016-11-07 at 11 57 19 am" src="https://cloud.githubusercontent.com/assets/6515165/20069247/700375e4-a4e1-11e6-8ad7-bd177b6b16c5.png">

**Comment by bdash** [comment]
We'd greatly appreciate if you can share an app with us that reproduces this. Even a pre-built copy of an app that reproduces this would be valuable. Feel free to share a sample project or pre-built app that reproduces this with us at help@realm.io.

**Comment by pauluhn** [comment]
Will do. Btw, I updated to RealmSwift 2.0.3 and same crash. Thanks for the followup.

**Comment by pauluhn** [comment]
I sent an email. Please let me know if you did not get it or need any additional info.

**Comment by jpsim** [comment]
Thanks for making that sample project, @pauluhn. I've been able to reproduce the crash. We're looking into it.

**Comment by n8tr** [comment]
We are experiencing what appears to be this same problem with 2.0.3.  
```
Crashed: RLMRealm notification listener EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x583a4449204c4c97
```

```
Crashed: RLMRealm notification listener
0  Realm                          0x102146c40 realm::FloatDoubleNode<realm::Column<double>, realm::GreaterEqual>::find_first_local(unsigned long, unsigned long) + 604
1  Realm                          0x10214ed6c realm::ParentNode::aggregate_local(realm::QueryStateBase*, unsigned long, unsigned long, unsigned long, realm::SequentialGetterBase*) + 156
2  Realm                          0x1020fb41c realm::Query::aggregate_internal(realm::Action, realm::DataType, bool, realm::ParentNode*, realm::QueryStateBase*, unsigned long, unsigned long, realm::SequentialGetterBase*) const + 312
3  Realm                          0x1020fc9d0 realm::Query::find_all(realm::TableViewBase&, unsigned long, unsigned long, unsigned long) const + 432
4  Realm                          0x1020fbbb8 realm::Query::find_all(unsigned long, unsigned long, unsigned long) + 108
5  Realm                          0x101f20f08 realm::_impl::ResultsNotifier::run() + 72
6  Realm                          0x101f15240 realm::_impl::RealmCoordinator::run_async_notifiers() + 1192
7  Realm                          0x101f14d44 realm::_impl::RealmCoordinator::on_change() + 24
8  Realm                          0x101efe334 realm::_impl::ExternalCommitHelper::listen() + 172
9  Realm                          0x101eff410 std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0>::operator()() + 28
10 Realm                          0x101eff398 std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >::__execute() + 28
11 Realm                          0x101eff560 std::__1::__thread_proxy<std::__1::tuple<void (std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >::*)(), std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >*> >(void*, void*) + 84
12 libsystem_pthread.dylib        0x18d123860 _pthread_body + 240
13 libsystem_pthread.dylib        0x18d123770 _pthread_body + 282
14 libsystem_pthread.dylib        0x18d120dbc thread_start + 4
```

**Comment by rrrlasse** [comment]
Fixed by https://github.com/realm/realm-core/pull/2314 :)

**Comment by pauluhn** [comment]
No longer crashing on 2.1.1... Thanks!

**Comment by jpsim** [comment]
Realm Cocoa 2.1.1 was released last week and addresses this. https://github.com/realm/realm-cocoa/releases/tag/v2.1.1
