### ISSUE TITLE
Cocoapods update to 2.3.x and 2.4.x fail

### ISSUE THREAD

**Issue by exsortis** [realm/realm-cocoa#4596]
## Goals

What do you want to achieve?

Update Pods in project with Realm >= 2.3

## Expected Results

Proper update of Pods in project.

## Actual Results

```
-> Installing Realm 2.4.0 (was 2.1.2)
 > Git download
 > Git download
     $ /usr/local/bin/git clone https://github.com/realm/realm-cocoa.git
     /var/folders/mc/63p3khl53ybfs7xcfc6spbr40000gn/T/d20170127-57186-3xvwl0 --template= --single-branch --depth 1 --branch v2.4.0
     Cloning into '/var/folders/mc/63p3khl53ybfs7xcfc6spbr40000gn/T/d20170127-57186-3xvwl0'...
     Note: checking out 'a0c5399f7344a3e7b0af4cda898635a00d6d26e6'.

     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by performing another checkout.

     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -b with the checkout command again. Example:

       git checkout -b <new-branch-name>

     $ /usr/local/bin/git -C /var/folders/mc/63p3khl53ybfs7xcfc6spbr40000gn/T/d20170127-57186-3xvwl0 submodule update --init --recursive
     Submodule 'Realm/ObjectStore' (https://github.com/realm/realm-object-store.git) registered for path 'Realm/ObjectStore'
     Cloning into '/private/var/folders/mc/63p3khl53ybfs7xcfc6spbr40000gn/T/d20170127-57186-3xvwl0/Realm/ObjectStore'...
     Submodule path 'Realm/ObjectStore': checked out '1c0db48c1d53ed28f6238c73da662a2716f442c0'
     Submodule 'external/catch' (https://github.com/philsquared/Catch) registered for path 'Realm/ObjectStore/external/catch'
     Submodule 'external/pegtl' (https://github.com/ColinH/PEGTL) registered for path 'Realm/ObjectStore/external/pegtl'
     Cloning into '/private/var/folders/mc/63p3khl53ybfs7xcfc6spbr40000gn/T/d20170127-57186-3xvwl0/Realm/ObjectStore/external/catch'...
     Cloning into '/private/var/folders/mc/63p3khl53ybfs7xcfc6spbr40000gn/T/d20170127-57186-3xvwl0/Realm/ObjectStore/external/pegtl'...
     Submodule path 'Realm/ObjectStore/external/catch': checked out 'f294c9847272b1b92c5119a6f711e57113b5f231'
     Submodule path 'Realm/ObjectStore/external/pegtl': checked out '3c4128a7e7e1288eb746418ea60c41477358f26a'
 > Running prepare command
   $ /bin/bash -c  set -e sh build.sh cocoapods-setup
[!] /bin/bash -c
set -e
sh build.sh cocoapods-setup



/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.rc.1/lib/cocoapods/executable.rb:69:in `execute_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.rc.1/lib/cocoapods/executable.rb:27:in `block in executable'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.rc.1/lib/cocoapods/installer/pod_source_preparer.rb:66:in `block (2 levels) in run_prepare_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.rc.1/lib/cocoapods/installer/pod_source_preparer.rb:60:in `chdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.rc.1/lib/cocoapods/installer/pod_source_preparer.rb:60:in `block in run_prepare_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.rc.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.rc.1/lib/cocoapods/installer/pod_source_preparer.rb:59:in `run_prepare_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.rc.1/lib/cocoapods/installer/pod_source_preparer.rb:37:in `prepare!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.rc.1/lib/cocoapods/downloader/cache.rb:202:in `copy_and_clean'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.rc.1/lib/cocoapods/downloader/cache.rb:159:in `block (2 levels) in uncached_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.rc.1/lib/cocoapods/downloader/cache.rb:157:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.rc.1/lib/cocoapods/downloader/cache.rb:157:in `block in uncached_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.rc.1/lib/cocoapods/downloader/cache.rb:181:in `call'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.rc.1/lib/cocoapods/downloader/cache.rb:181:in `in_tmpdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.rc.1/lib/cocoapods/downloader/cache.rb:153:in `uncached_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.rc.1/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.rc.1/lib/cocoapods/downloader.rb:42:in `download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.rc.1/lib/cocoapods/installer/pod_source_installer.rb:120:in `download_source'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.rc.1/lib/cocoapods/installer/pod_source_installer.rb:60:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.rc.1/lib/cocoapods/installer.rb:355:in `install_source_of_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.rc.1/lib/cocoapods/installer.rb:322:in `block (2 levels) in install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.rc.1/lib/cocoapods/user_interface.rb:85:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.rc.1/lib/cocoapods/installer.rb:321:in `block in install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.rc.1/lib/cocoapods/installer.rb:313:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.rc.1/lib/cocoapods/installer.rb:313:in `install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.rc.1/lib/cocoapods/installer.rb:159:in `block in download_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.rc.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.rc.1/lib/cocoapods/installer.rb:157:in `download_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.rc.1/lib/cocoapods/installer.rb:111:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.rc.1/lib/cocoapods/command/update.rb:81:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.rc.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.rc.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

## Steps to Reproduce

What are steps we can follow to reproduce this issue?

1. `pod update`

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: >= 2.3

Xcode version: 8.2.1

iOS/OSX version: macOS 10.12.4 beta

Dependency manager + version: CocoaPods 1.2.0.rc.1

**Comment by istx25** [comment]
This isn't a problem that's specifically related to Realm. I managed to create a new Xcode project using all of the same tools you are. [Here's a copy of the project](https://github.com/realm/realm-cocoa/files/735822/RealmTest.zip). I recommend reinstalling CocoaPods and filing an issue with them too.

1. `pod install`
2. `pod update`

Both worked for me. I'm closing but let me know if you need any more help.

**Comment by exsortis** [comment]
This is still not working. I've tried both CocoaPods 1.1.1 and 1.2.0.rc.1, and it always fails when trying to install or update Realm 2.2 or 2.3. If I specify `pod 'RealmSwift', '< 2.2'`, it works fine. That feels a lot like a Realm issue and not a CocoaPods issue.

**Comment by jpsim** [comment]
Apologies for closing this before helping you resolve your issue.

Could you please run `sudo xcodebuild -license accept` and try running `pod install --verbose`?

It's also possible that CocoaPods has stale cache, you you could try deleting that to see if it helps.

**Comment by exsortis** [comment]
Forcing the license acceptance seems to have done the trick. I think there might have something screwy on my machine with having both regular Xcode and the 8.3 beta installed at the same time. Thanks!
