### ISSUE TITLE
Errno::ENOENT - No such file or directory - /Users/xxxx/dev/xxxx/xxxx/Pods/Realm/Realm/module.modulemap

### ISSUE THREAD

**Issue by i-schuetz** [realm/realm-cocoa#4786]
## Goals
Update a pod (not Realm). 

## Expected Results
The pod is updated

## Actual Results
Causes an error, with Realm apparently:

> 
> Errno::ENOENT - No such file or directory - /Users/xxxx/dev/xxxx/xxxx/Pods/Realm/Realm/module.modulemap
> /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1380:in `initialize'
> /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1380:in `open'
> /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1380:in `copy_file'
> /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:477:in `copy_file'
> /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:394:in `block in cp'
> /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1558:in `block in fu_each_src_dest'
> /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1574:in `fu_each_src_dest0'
> /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1556:in `fu_each_src_dest'
> /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:393:in `cp'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:345:in `block in create_module_map'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:142:in `message'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:344:in `create_module_map'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:27:in `block in install!'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:142:in `message'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:19:in `install!'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:155:in `block (2 levels) in install_libraries'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:153:in `each'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:153:in `block in install_libraries'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:142:in `message'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:152:in `install_libraries'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:64:in `generate!'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:179:in `block in generate_pods_project'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:64:in `section'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:178:in `generate_pods_project'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:115:in `install!'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/command/update.rb:81:in `run'
> /Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/command.rb:52:in `run'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/bin/pod:55:in `<top (required)>'
> /usr/local/bin/pod:23:in `load'
> /usr/local/bin/pod:23:in `<main>'
> 

## Steps to Reproduce
`pod update MyPod`

The podfile has following pods, in this order:
```
  pod 'MyPod', :git => 'https://github.com/xxxx/xxxx.git', :branch => "master"
  pod 'Alamofire', '~> 4.0'
  pod 'AlamofireImage', '~> 3.1'
  pod 'DKChainableAnimationKit', '~> 2.0.0'
  pod 'SnapKit', '~> 3.0.2'
  pod 'Bond', '~> 5.0'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'Eureka', '~> 2.0.0-beta.1'
  pod 'HidingNavigationBar', '~> 1.0'
  pod 'RealmSwift'
  pod 'SwiftKeychainWrapper'
  pod 'SwiftyBeaver'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Fabric'
  pod 'TwitterKit'
  pod 'TwitterCore'
  pod 'Google/SignIn'
  pod 'NextGrowingTextView'
```

## Version of Realm and Tooling

> ProductName:	Mac OS X
> ProductVersion:	10.12.3
> BuildVersion:	16D32
> 
> /Applications/Xcode.app/Contents/Developer
> Xcode 8.3
> Build version 8E162
> 
> /usr/local/bin/pod
> 1.2.0
> Realm (2.0.3)
> RealmSwift (2.0.3)
> 
> /bin/bash
> GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
> 
> /usr/local/bin/carthage
> 0.18.1
> (not in use here)
> 
> /usr/bin/git
> git version 2.11.0 (Apple Git-81)

I don't know if this is a Realm or CocoaPods issue. The CocoaPods version is the most recent. Realm is a bit outdated, but that shouldn't be the reason of the problem?

**Comment by i-schuetz** [comment]
Cleaning CocoaPods cache and re-installing everything fixed it.
