### ISSUE TITLE
Not Able to Install Realm using Pod install

### ISSUE THREAD

**Issue by deepakinflectica** [realm/realm-cocoa#5532]
I am not able to install Realm using Pod install.

Tried both Pod install and Pod Update calls.. I have added the entire verbose output generated below for reference.

```
pod update --verbose
Update all pods
  Preparing

Updating local specs repositories

Updating spec repo `master`
  $ /usr/local/bin/git -C /Users/deepaksinha/.cocoapods/repos/master fetch origin --progress
  $ /usr/local/bin/git -C /Users/deepaksinha/.cocoapods/repos/master rev-parse --abbrev-ref HEAD
  master
  $ /usr/local/bin/git -C /Users/deepaksinha/.cocoapods/repos/master reset --hard origin/master
  HEAD is now at a2c7828c919 [Add] Clappr 0.7.3

CocoaPods 1.4.0.rc.1 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.4.0.rc.1


Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-WooCommerceLib`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-WooCommerceLibTests`: (``)

Finding Podfile changes
  A RealmSwift
  - Alamofire
  - LNRSimpleNotifications
  - SwiftyJSON
  - TDOAuth

Resolving dependencies of `Podfile`

Comparing resolved specification to the sandbox manifest
  A Realm
  A RealmSwift
  M Alamofire
  - LNRSimpleNotifications
  - OMGHTTPURLRQ
  - SwiftyJSON
  - TDOAuth

Downloading dependencies

-> Installing Alamofire 4.6.0 (was 4.5.1)
  > Copying Alamofire from `/Users/deepaksinha/Library/Caches/CocoaPods/Pods/Release/Alamofire/4.6.0-f41a5` to `Pods/Alamofire`

-> Using LNRSimpleNotifications (0.8.0)

-> Using OMGHTTPURLRQ (3.2.2)

-> Installing Realm (3.0.2)
 > Git download
 > Git download
     $ /usr/local/bin/git clone https://github.com/realm/realm-cocoa.git /var/folders/7k/l0sxhd016q965h80z7gtnlr80000gn/T/d20171221-14618-1nt7mwi --template= --single-branch --depth 1 --branch v3.0.2
     Cloning into '/var/folders/7k/l0sxhd016q965h80z7gtnlr80000gn/T/d20171221-14618-1nt7mwi'...
     Note: checking out '13a3cb44c10436d4fb575bfcddc879698ae956e3'.
     
     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by performing another checkout.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -b with the checkout command again. Example:
     
       git checkout -b <new-branch-name>
     
     $ /usr/local/bin/git -C /var/folders/7k/l0sxhd016q965h80z7gtnlr80000gn/T/d20171221-14618-1nt7mwi submodule update --init --recursive
     Submodule 'Realm/ObjectStore' (https://github.com/realm/realm-object-store.git) registered for path 'Realm/ObjectStore'
     Cloning into '/private/var/folders/7k/l0sxhd016q965h80z7gtnlr80000gn/T/d20171221-14618-1nt7mwi/Realm/ObjectStore'...
     Submodule path 'Realm/ObjectStore': checked out '136b3a32a218f50275f1183ed078b31945a9e29f'
     Submodule 'external/catch' (https://github.com/philsquared/Catch) registered for path 'Realm/ObjectStore/external/catch'
     Submodule 'external/pegtl' (https://github.com/ColinH/PEGTL) registered for path 'Realm/ObjectStore/external/pegtl'
     Cloning into '/private/var/folders/7k/l0sxhd016q965h80z7gtnlr80000gn/T/d20171221-14618-1nt7mwi/Realm/ObjectStore/external/catch'...
     Cloning into '/private/var/folders/7k/l0sxhd016q965h80z7gtnlr80000gn/T/d20171221-14618-1nt7mwi/Realm/ObjectStore/external/pegtl'...
     Submodule path 'Realm/ObjectStore/external/catch': checked out 'ee67ac6b7c3595251342671485c65cf81d725896'
     Submodule path 'Realm/ObjectStore/external/pegtl': checked out '3c4128a7e7e1288eb746418ea60c41477358f26a'
 > Running prepare command
   $ /bin/bash -c  set -e sh build.sh cocoapods-setup
   core is not a symlink. Deleting...
   Downloading dependency: sync 2.1.1
   tar (child): xz: Cannot exec: No such file or directory
   tar (child): Error is not recoverable: exiting now
   tar: Child returned status 2
   tar: Error is not recoverable: exiting now
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: sync 2.1.1
tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now


/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/executable.rb:69:in `execute_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/executable.rb:27:in `block in executable'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/pod_source_preparer.rb:66:in `block (2 levels) in run_prepare_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/pod_source_preparer.rb:60:in `chdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/pod_source_preparer.rb:60:in `block in run_prepare_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/pod_source_preparer.rb:59:in `run_prepare_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/pod_source_preparer.rb:37:in `prepare!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/downloader/cache.rb:202:in `copy_and_clean'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/downloader/cache.rb:159:in `block (2 levels) in uncached_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/downloader/cache.rb:157:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/downloader/cache.rb:157:in `block in uncached_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/downloader/cache.rb:181:in `call'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/downloader/cache.rb:181:in `in_tmpdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/downloader/cache.rb:153:in `uncached_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/downloader.rb:42:in `download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/pod_source_installer.rb:120:in `download_source'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/pod_source_installer.rb:60:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:364:in `install_source_of_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:329:in `block (2 levels) in install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:85:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:328:in `block in install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:320:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:320:in `install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:163:in `block in download_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:161:in `download_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:117:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/command/update.rb:81:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by phoney** [comment]
This is probably a problem with your installation of cocoapods or ruby or both.  I have:

$ pod --version
1.3.1
$ which ruby
/usr/local/bin/ruby
$ ruby --version
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]

**Comment by bdash** [comment]
The relevant portion of the error appears to be:
```
   tar (child): xz: Cannot exec: No such file or directory
   tar (child): Error is not recoverable: exiting now
   tar: Child returned status 2
   tar: Error is not recoverable: exiting now
```

The fact that `tar` is trying to invoke `xz` suggests to me that you have a nonstandard version of `tar` installed (Apple's system `tar` gets its support for `xz` files via libarchive rather than an external program). If you have `tar` installed via something like Homebrew, I'd suggest also installing `xz` via the same means, then trying to install Realm again.

**Comment by stennie** [comment]
Closing this issue due to no response. Feel free to reopen if additional information can be provided.
