### ISSUE TITLE
Failed Cocoapods installation: core/librealm-ios.a LZMA Corrupted input data

### ISSUE THREAD

**Issue by freak4pc** [realm/realm-cocoa#5569]
## Goals
Install RealmSwift via Cocoapods.

## Expected Results
Installation to run smooth with no expected errors. 

## Actual Results
Getting the following error while installing.
This seems rather new, wasn't happening a few days ago: 

```
[!] /bin/bash -c
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: sync 2.1.1
core/librealm-ios.a: Lzma library error: Corrupted input data
tar: Error exit delayed from previous errors.
```

<img width="452" alt="e01c24d9-1c77-4d92-b83b-bdea476b823b" src="https://user-images.githubusercontent.com/605076/34893071-492dc652-f7e4-11e7-84f5-da11228732fb.png">

## Version of Realm and Tooling
Realm 3.0.2

## Dependency manager + version: ?
Cocoapods 1.3.1 and 1.4.0.rc.1 tried

## Podfile
```
platform :ios, '11.0'

target 'PlaygroundTest' do
  use_frameworks!
  pod 'RealmSwift', '~> 3.0'
end
```

## Verbose log with repo-update
```
pod install --repo-update --verbose
  Preparing

Updating local specs repositories

Updating spec repo `master`
  $ /usr/local/bin/git -C /Users/freak4pc/.cocoapods/repos/master fetch origin --progress
  remote: Counting objects: 27, done.
  remote: Compressing objects: 100% (24/24), done.
  remote: Total 27 (delta 16), reused 0 (delta 0), pack-reused 0
  From https://github.com/CocoaPods/Specs
     61cafff3399..6391f8963bc  master     -> origin/master
  $ /usr/local/bin/git -C /Users/freak4pc/.cocoapods/repos/master rev-parse --abbrev-ref HEAD
  master
  $ /usr/local/bin/git -C /Users/freak4pc/.cocoapods/repos/master reset --hard origin/master
  HEAD is now at 6391f8963bc [Add] PromiseKit 1.7.4

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-TestPlayground`: (``)

Resolving dependencies of `Podfile`

Comparing resolved specification to the sandbox manifest
  A Realm
  A RealmSwift

Downloading dependencies

-> Installing Realm (3.0.2)
 > Git download
 > Git download
     $ /usr/local/bin/git clone https://github.com/realm/realm-cocoa.git /var/folders/n8/mtvdkyqn1fz6yqwy238wncv00000gn/T/d20180112-81907-udooq2
     --template= --single-branch --depth 1 --branch v3.0.2
     Cloning into '/var/folders/n8/mtvdkyqn1fz6yqwy238wncv00000gn/T/d20180112-81907-udooq2'...
     Note: checking out '13a3cb44c10436d4fb575bfcddc879698ae956e3'.

     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by performing another checkout.

     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -b with the checkout command again. Example:

       git checkout -b <new-branch-name>

     $ /usr/local/bin/git -C /var/folders/n8/mtvdkyqn1fz6yqwy238wncv00000gn/T/d20180112-81907-udooq2 submodule update --init --recursive
     Submodule 'Realm/ObjectStore' (https://github.com/realm/realm-object-store.git) registered for path 'Realm/ObjectStore'
     Cloning into '/private/var/folders/n8/mtvdkyqn1fz6yqwy238wncv00000gn/T/d20180112-81907-udooq2/Realm/ObjectStore'...
     Submodule path 'Realm/ObjectStore': checked out '136b3a32a218f50275f1183ed078b31945a9e29f'
     Submodule 'external/catch' (https://github.com/philsquared/Catch) registered for path 'Realm/ObjectStore/external/catch'
     Submodule 'external/pegtl' (https://github.com/ColinH/PEGTL) registered for path 'Realm/ObjectStore/external/pegtl'
     Cloning into '/private/var/folders/n8/mtvdkyqn1fz6yqwy238wncv00000gn/T/d20180112-81907-udooq2/Realm/ObjectStore/external/catch'...
     Cloning into '/private/var/folders/n8/mtvdkyqn1fz6yqwy238wncv00000gn/T/d20180112-81907-udooq2/Realm/ObjectStore/external/pegtl'...
     Submodule path 'Realm/ObjectStore/external/catch': checked out 'ee67ac6b7c3595251342671485c65cf81d725896'
     Submodule path 'Realm/ObjectStore/external/pegtl': checked out '3c4128a7e7e1288eb746418ea60c41477358f26a'
 > Running prepare command
   $ /bin/bash -c  set -e sh build.sh cocoapods-setup
   core is not a symlink. Deleting...
   Downloading dependency: sync 2.1.1
   core/librealm-ios.a: Lzma library error: Corrupted input data
   tar: Error exit delayed from previous errors.
[!] /bin/bash -c
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: sync 2.1.1
core/librealm-ios.a: Lzma library error: Corrupted input data
tar: Error exit delayed from previous errors.


/Users/freak4pc/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0.rc.1/lib/cocoapods/executable.rb:69:in `execute_command'
/Users/freak4pc/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0.rc.1/lib/cocoapods/executable.rb:27:in `block in executable'
/Users/freak4pc/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0.rc.1/lib/cocoapods/installer/pod_source_preparer.rb:66:in `block (2 levels) in run_prepare_command'
/Users/freak4pc/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0.rc.1/lib/cocoapods/installer/pod_source_preparer.rb:60:in `chdir'
/Users/freak4pc/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0.rc.1/lib/cocoapods/installer/pod_source_preparer.rb:60:in `block in run_prepare_command'
/Users/freak4pc/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0.rc.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/freak4pc/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0.rc.1/lib/cocoapods/installer/pod_source_preparer.rb:59:in `run_prepare_command'
/Users/freak4pc/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0.rc.1/lib/cocoapods/installer/pod_source_preparer.rb:37:in `prepare!'
/Users/freak4pc/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0.rc.1/lib/cocoapods/downloader/cache.rb:202:in `copy_and_clean'
/Users/freak4pc/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0.rc.1/lib/cocoapods/downloader/cache.rb:159:in `block (2 levels) in uncached_pod'
/Users/freak4pc/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0.rc.1/lib/cocoapods/downloader/cache.rb:157:in `each'
/Users/freak4pc/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0.rc.1/lib/cocoapods/downloader/cache.rb:157:in `block in uncached_pod'
/Users/freak4pc/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0.rc.1/lib/cocoapods/downloader/cache.rb:181:in `in_tmpdir'
/Users/freak4pc/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0.rc.1/lib/cocoapods/downloader/cache.rb:153:in `uncached_pod'
/Users/freak4pc/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0.rc.1/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Users/freak4pc/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0.rc.1/lib/cocoapods/downloader.rb:42:in `download'
/Users/freak4pc/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0.rc.1/lib/cocoapods/installer/pod_source_installer.rb:120:in `download_source'
/Users/freak4pc/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0.rc.1/lib/cocoapods/installer/pod_source_installer.rb:60:in `install!'
/Users/freak4pc/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0.rc.1/lib/cocoapods/installer.rb:365:in `install_source_of_pod'
/Users/freak4pc/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0.rc.1/lib/cocoapods/installer.rb:330:in `block (2 levels) in install_pod_sources'
/Users/freak4pc/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0.rc.1/lib/cocoapods/user_interface.rb:85:in `titled_section'
/Users/freak4pc/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0.rc.1/lib/cocoapods/installer.rb:329:in `block in install_pod_sources'
/Users/freak4pc/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0.rc.1/lib/cocoapods/installer.rb:321:in `each'
/Users/freak4pc/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0.rc.1/lib/cocoapods/installer.rb:321:in `install_pod_sources'
/Users/freak4pc/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0.rc.1/lib/cocoapods/installer.rb:164:in `block in download_dependencies'
/Users/freak4pc/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0.rc.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/freak4pc/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0.rc.1/lib/cocoapods/installer.rb:162:in `download_dependencies'
/Users/freak4pc/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0.rc.1/lib/cocoapods/installer.rb:117:in `install!'
/Users/freak4pc/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0.rc.1/lib/cocoapods/command/install.rb:41:in `run'
/Users/freak4pc/.rvm/gems/ruby-2.4.1/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/freak4pc/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0.rc.1/lib/cocoapods/command.rb:52:in `run'
/Users/freak4pc/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0.rc.1/bin/pod:55:in `<top (required)>'
/Users/freak4pc/.rvm/gems/ruby-2.4.1/bin/pod:23:in `load'
/Users/freak4pc/.rvm/gems/ruby-2.4.1/bin/pod:23:in `<main>'
/Users/freak4pc/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/Users/freak4pc/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by freak4pc** [comment]
Well, I restarted and it seems fine now. ¯\_(ツ)_/¯

Strange because switching 4 different networks didn't help. 

Still good to have for someone else to might bump into this thread accidentally :)
