### ISSUE TITLE
`pod install` for RealmSwift fails

### ISSUE THREAD

**Issue by jojonarte** [realm/realm-cocoa#5766]
## Goals
* install RealmSwift

## Expected Results
* RealmSwift and Realm installed

## Actual Results
* fails:
 ```
Installing Realm (3.5.0)
 > Git download
 > Git download
     $ /usr/local/bin/git clone https://github.com/realm/realm-cocoa.git
     /var/folders/c7/ktycgkjs449c7zxdrmq0fd_m0000gn/T/d20180515-38426-wbfv1n --template=
     --single-branch --depth 1 --branch v3.5.0
     Cloning into '/var/folders/c7/ktycgkjs449c7zxdrmq0fd_m0000gn/T/d20180515-38426-wbfv1n'...
     Note: checking out '12b5278db62df7b337af94297b57303087f10428'.
     
     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by performing another checkout.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -b with the checkout command again. Example:
     
       git checkout -b <new-branch-name>
     
     $ /usr/local/bin/git -C /var/folders/c7/ktycgkjs449c7zxdrmq0fd_m0000gn/T/d20180515-38426-wbfv1n
     submodule update --init --recursive
     Submodule 'Realm/ObjectStore' (https://github.com/realm/realm-object-store.git) registered for path 'Realm/ObjectStore'
     Cloning into 'Realm/ObjectStore'...
     Submodule path 'Realm/ObjectStore': checked out 'fa7ce8b6a8f9ae63753e1307ffe3c9caa40b172d'
     Submodule 'external/catch' (https://github.com/philsquared/Catch) registered for path 'external/catch'
     Cloning into 'external/catch'...
     error: RPC failed; result=18, HTTP code = 200
     fatal: The remote end hung up unexpectedly
     fatal: early EOF
     fatal: index-pack failed
     Clone of 'https://github.com/philsquared/Catch' into submodule path 'external/catch' failed
     Failed to recurse into submodule path 'Realm/ObjectStore'

[!] Error installing Realm
[!] /usr/local/bin/git -C /var/folders/c7/ktycgkjs449c7zxdrmq0fd_m0000gn/T/d20180515-38426-wbfv1n submodule update --init --recursive

Submodule 'Realm/ObjectStore' (https://github.com/realm/realm-object-store.git) registered for path 'Realm/ObjectStore'
Submodule path 'Realm/ObjectStore': checked out 'fa7ce8b6a8f9ae63753e1307ffe3c9caa40b172d'
Submodule 'external/catch' (https://github.com/philsquared/Catch) registered for path 'external/catch'
Cloning into 'Realm/ObjectStore'...
Cloning into 'external/catch'...
error: RPC failed; result=18, HTTP code = 200
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Clone of 'https://github.com/philsquared/Catch' into submodule path 'external/catch' failed
Failed to recurse into submodule path 'Realm/ObjectStore'


/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.0/lib/cocoapods/downloader.rb:142:in `rescue in execute_command'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.0/lib/cocoapods/downloader.rb:140:in `execute_command'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-downloader-1.2.0/lib/cocoapods-downloader/base.rb:154:in `block in executable'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-downloader-1.2.0/lib/cocoapods-downloader/git.rb:132:in `target_git'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-downloader-1.2.0/lib/cocoapods-downloader/git.rb:93:in `update_submodules'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-downloader-1.2.0/lib/cocoapods-downloader/git.rb:80:in `block in clone'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.0/lib/cocoapods/downloader.rb:173:in `block in ui_sub_action'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.0/lib/cocoapods/downloader.rb:172:in `ui_sub_action'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-downloader-1.2.0/lib/cocoapods-downloader/git.rb:77:in `clone'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-downloader-1.2.0/lib/cocoapods-downloader/git.rb:45:in `download!'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-downloader-1.2.0/lib/cocoapods-downloader/base.rb:82:in `block in download'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.0/lib/cocoapods/downloader.rb:157:in `block in ui_action'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.0/lib/cocoapods/downloader.rb:156:in `ui_action'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-downloader-1.2.0/lib/cocoapods-downloader/base.rb:80:in `download'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.0/lib/cocoapods/downloader.rb:108:in `download_source'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.0/lib/cocoapods/downloader.rb:75:in `download_request'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.0/lib/cocoapods/downloader/cache.rb:171:in `download'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.0/lib/cocoapods/downloader/cache.rb:154:in `block in uncached_pod'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.0/lib/cocoapods/downloader/cache.rb:181:in `in_tmpdir'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.0/lib/cocoapods/downloader/cache.rb:153:in `uncached_pod'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.0/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.0/lib/cocoapods/downloader.rb:42:in `download'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/pod_source_installer.rb:121:in `download_source'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/pod_source_installer.rb:60:in `install!'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.0/lib/cocoapods/installer.rb:374:in `install_source_of_pod'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.0/lib/cocoapods/installer.rb:339:in `block (2 levels) in install_pod_sources'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.0/lib/cocoapods/user_interface.rb:85:in `titled_section'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.0/lib/cocoapods/installer.rb:338:in `block in install_pod_sources'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.0/lib/cocoapods/installer.rb:321:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.0/lib/cocoapods/installer.rb:321:in `install_pod_sources'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.0/lib/cocoapods/installer.rb:164:in `block in download_dependencies'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.0/lib/cocoapods/installer.rb:162:in `download_dependencies'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.0/lib/cocoapods/installer.rb:117:in `install!'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.0/lib/cocoapods/command/install.rb:41:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.0/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>
```

## Steps to Reproduce
pod version : 1.5.0
ruby version: ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin15]

## Code Sample
PodFile:
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'AppTest' do
    
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for AppTest
    pod 'RealmSwift'
    
    target 'CaptureQATests' do
        inherit! :search_paths
        # Pods for testing
    end
end
```

**Comment by jojonarte** [comment]
I've fixed this by specifying a lower RealmSwift version.

**Comment by yuanjilee** [comment]
try `pod repo update` first

**Comment by iOSPrincekin** [comment]
try   ` git config --global http.postBuffer 114288000`

**Comment by 2227322717** [comment]
same issue, help me out pls
