### ISSUE TITLE
CocoaPods error when upgrading to 3.17.3

### ISSUE THREAD

**Issue by iDevid** [realm/realm-cocoa#6218]
### Report

* What did you do?
I run "pod update"

* What did you expect to happen?
Just update the pods

* What happened instead?
The installation fails, below there is the stack trace from cocoapods

### Stack

```
   CocoaPods : 1.7.5
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15 (19A526h)
       Xcode : 10.3 (10G8)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 20f0ecb2d27ce25e3573074edce9f6212247610a
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '10.0'

inhibit_all_warnings!

target 'App' do

  use_frameworks!

  pod 'Alamofire'
  pod 'AlignedCollectionViewFlowLayout'
  pod 'CarbonKit'
  pod 'Charts'
  pod 'Crashlytics'
  pod 'GoogleAnalytics'
  pod 'Google-Mobile-Ads-SDK'
  pod 'Fabric'
  pod 'Firebase'
  pod 'FirebaseMessaging'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/RemoteConfig'
  pod 'Hero'
  pod 'lottie-ios'
  pod 'RxCocoa'
  pod 'RxRealm'
  pod 'RxSwift'
  pod 'RxDataSources'
  pod 'RealmSwift'
  pod 'RxDataSources'
  pod 'RangeSeekSlider'
  pod 'SwiftyStoreKit'
  pod 'SwiftGifOrigin'
  pod 'SwipeCellKit'
  pod 'YoutubePlayer-in-WKWebView'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'RxSwift'
      target.build_configurations.each do |config|
        if config.name == 'Debug'
          config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['-D', 'TRACE_RESOURCES']
        end
      end
    end
  end
end
```

### Error

```
Errno::ENOENT - No such file or directory @ realpath_rec - /Users/userdir/app/Pods/Realm/Realm/RLMAccessor.h
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/project.rb:320:in `realpath'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/project.rb:320:in `realpath'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/project.rb:320:in `reference_for_path'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/project.rb:266:in `add_file_reference'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:220:in `block (2 levels) in add_file_accessors_paths_to_pods_group'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:219:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:219:in `block in add_file_accessors_paths_to_pods_group'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:210:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:210:in `add_file_accessors_paths_to_pods_group'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:93:in `block in add_source_files_references'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:145:in `message'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:92:in `add_source_files_references'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:46:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/pods_project_generator.rb:101:in `block in install_file_references'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:145:in `message'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/pods_project_generator.rb:99:in `install_file_references'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:17:in `generate!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:295:in `block in create_and_save_projects'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:290:in `create_and_save_projects'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:281:in `generate_pods_project'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:159:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/command/update.rb:62:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by MortyMerr** [comment]
I can reproduce this to, while installing 4.3.0

**Comment by leemaguire** [comment]
@MortyMerr Are you using the latest version of Cocoapods? Have you done a `pod repo update`?

Thanks,
Lee

**Comment by JonathanChen123** [comment]
Still reproduced it by using Cocoapods v1.9.3 after done 'pod update'

**Comment by ericjordanmossman** [comment]
@JonathanChen123 @MortyMerr @iDevid 
Have any of you experienced this with Realm >5.x?

**Comment by iDevid** [comment]
Actually no
