### ISSUE TITLE
pod install is not working with Objective-C realm pod 3.17.1. It shows permission denied at Running prepare command

### ISSUE THREAD

**Issue by ShreyashPromact** [realm/realm-cocoa#6220]
**Bugs**: When I executed pod install command, it gets failed at Virtual machine because of the **realm pod**. Right now, I am using **3.17.1** of the realm Objective-C. The virtual machine (where I am running this command) is **macOS-10.13**. The CocoaPods version is **1.7.5**.

## Goals
It should successfully execute the pod install along with realm 3.17.1 pod

## Expected Results
It should successfully execute the pod install along with realm 3.17.1 pod

## Actual Results
I got below error while executing pod install
**pod install --verbose**

````
-> Installing Realm (3.17.1)
 > Git download
 > Git download
     $ /usr/local/bin/git clone https://github.com/realm/realm-cocoa.git /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20190807-828-1pt3hzv --template= --single-branch --depth 1 --branch v3.17.1
     Cloning into '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20190807-828-1pt3hzv'...
     Note: checking out '466837115bd6c7324953e00daf3a9a681f3ee025'.
     
     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by performing another checkout.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -b with the checkout command again. Example:
     
       git checkout -b <new-branch-name>
     
     $ /usr/local/bin/git -C /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20190807-828-1pt3hzv submodule update --init --recursive
     Submodule 'Realm/ObjectStore' (https://github.com/realm/realm-object-store.git) registered for path 'Realm/ObjectStore'
     Cloning into '/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20190807-828-1pt3hzv/Realm/ObjectStore'...
     Submodule 'external/catch' (https://github.com/catchorg/Catch2) registered for path 'Realm/ObjectStore/external/catch'
     Cloning into '/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20190807-828-1pt3hzv/Realm/ObjectStore/external/catch'...
     Submodule path 'Realm/ObjectStore': checked out '13adc3afe177fb67afc8d3f63e0b2775df0a95b1'
     Submodule path 'Realm/ObjectStore/external/catch': checked out '6860c8def0ba7559bf077515b7a7ff63ad3444f8'
 > Running prepare command
   $ /bin/bash -c  set -e sh build.sh cocoapods-setup
   mkdir: /var/folders/yy/d215g62s727f4w2137t9jl2m0000gn/T/sync_bin: Permission denied
   core is not a symlink. Deleting...
   Downloading dependency: sync 4.6.3 from https://static.realm.io/downloads/sync/realm-sync-cocoa-4.6.3.tar.xz
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: sync 4.6.3 from https://static.realm.io/downloads/sync/realm-sync-cocoa-4.6.3.tar.xz
mkdir: /var/folders/yy/d215g62s727f4w2137t9jl2m0000gn/T/sync_bin: Permission denied

/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/executable.rb:73:in `execute_command'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/executable.rb:27:in `block in executable'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/pod_source_preparer.rb:66:in `block (2 levels) in run_prepare_command'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/pod_source_preparer.rb:60:in `chdir'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/pod_source_preparer.rb:60:in `block in run_prepare_command'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/pod_source_preparer.rb:59:in `run_prepare_command'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/pod_source_preparer.rb:37:in `prepare!'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/downloader/cache.rb:202:in `copy_and_clean'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/downloader/cache.rb:159:in `block (2 levels) in uncached_pod'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/downloader/cache.rb:157:in `each'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/downloader/cache.rb:157:in `block in uncached_pod'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/downloader/cache.rb:181:in `in_tmpdir'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/downloader/cache.rb:153:in `uncached_pod'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/downloader.rb:42:in `download'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/pod_source_installer.rb:109:in `download_source'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/pod_source_installer.rb:62:in `install!'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:545:in `install_source_of_pod'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:496:in `block (2 levels) in install_pod_sources'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:86:in `titled_section'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:495:in `block in install_pod_sources'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:478:in `each'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:478:in `install_pod_sources'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:235:in `block in download_dependencies'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:234:in `download_dependencies'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:157:in `install!'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/command/install.rb:51:in `run'
/usr/local/lib/ruby/gems/2.6.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
##[error]Bash exited with code '1'.
````

## Steps to Reproduce
add **pod 'Realm', '~>3.17.1'** in podfile
execute `pod install`

**Note:** This is working in my local Mac machine, but I am having an issue with the virtual machine while executing command `pod install`

## Version of Realm and Tooling
Realm framework version: `3.17.1`

Realm Object Server version: `Not required`

Xcode version: `10.2`

iOS/OSX version: `10.13`

Dependency manager + version: `1.7.5`

**Comment by ShreyashPromact** [comment]
FYI, If I do comment on realm pod, pod install command executed successfully. But with realm pod, it creates an error in the same command.

**Comment by ShreyashPromact** [comment]
Can I have an update on this issue please.

**Comment by bmunkholm** [comment]
@ShreyashPromact What's the difference between your local Mac where it works and your Virtual Machine? It's hard for us to troubleshoot that as we can't reproduce your issue. The only obvious thing to say is that it's related to access rights on your virtual machine. What have you done to troubleshoot that?

**Comment by jsflax** [comment]
Right, I am unable to reproduce this. At first glance, this appears to be a permissions issue on your Virtual Machine.

**Comment by ShreyashPromact** [comment]
Yes. That seems permission related issue to me as well. But I am wondering how other pods gets installed with the same configuration but realm does not.

**Comment by tgoyne** [comment]
Your temporary directory is not writable by the current user, which is a configuration problem in your VM. Most pods don't need to write anything to the tempdir during installation so this won't effect them.

**Comment by ShreyashPromact** [comment]
I had found that the directory was writable. Other pods are creating a new directory inside it, and also generate files, whatever is required. Somehow it was getting failed with the realm only.

Anyway, I have to change the OS version on the virtual machine and it gets resolved. I don't know why it was not working on the previous OS.

Thanks for your help.

**Comment by ShreyashPromact** [comment]
@tgoyne 
Just for an update. The issue was the one you mentioned above. I have given permission to the temp directory and now It is working fine.

Thanks.
