### ISSUE TITLE
pod install fails as of Realm 10.1.2 - No such file or directory

### ISSUE THREAD

**Issue by DouweBos** [realm/realm-cocoa#6943]
##  Goals
Tried to run pod install on an example app that implements my SDK. Pod install fails when generating the pods project. Works on Realm 10.1.1, fails on 10.1.2 & 10.1.3.

## Expected Results
Pod installs

## Actual Results

```
Errno::ENOENT - No such file or directory @ realpath_rec - /Users/Douwe/Work/Reelgood/Projects/RGKit/RGKitSDK/Example/Pods/Realm/Realm/RLMAccessor.h
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/project.rb:326:in `realpath'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/project.rb:326:in `realpath'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/project.rb:326:in `reference_for_path'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/project.rb:269:in `add_file_reference'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:224:in `block (2 levels) in add_file_accessors_paths_to_pods_group'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:223:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:223:in `block in add_file_accessors_paths_to_pods_group'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:213:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:213:in `add_file_accessors_paths_to_pods_group'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:96:in `block in add_source_files_references'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:145:in `message'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:95:in `add_source_files_references'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:46:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:102:in `block in install_file_references'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:145:in `message'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:100:in `install_file_references'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:17:in `generate!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:312:in `block in create_and_save_projects'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:307:in `create_and_save_projects'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:299:in `generate_pods_project'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:178:in `integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:166:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```
## Version of Realm and Tooling

Realm framework version: 10.1.1 - 10.1.2 - 10.1.3

Xcode version: 12.1 (12A7403)

iOS/OSX version: Mac OS X 10.15.6 (19G2021)

Dependency manager + version: cocoapods 1.10.0

**Comment by jsflax** [comment]
Could you try doing a full clean and deintegrate before trying to build again?

**Comment by DouweBos** [comment]
Yeah already tried `pod deintegrate`
Ran into this within multiple projects

**Comment by jsflax** [comment]
Have you tried clearing your pod cache as well?

**Comment by DouweBos** [comment]
trying it again right now. Not the greatest internet here in Cork so I am hoping the download just failed

**Comment by DouweBos** [comment]
......
Should have tried that again before opening an issue. That seems to have done the trick.

**Comment by jsflax** [comment]
No worries. I'll have to tell our friends in Cork to work on their download speeds 😅

**Comment by DouweBos** [comment]
Nah, just tell Eir to get the s together.
