### ISSUE TITLE
Cannot install RealmSwift on CocoaPods under the macOS environment of Github Actions.

### ISSUE THREAD

**Issue by Econa77** [realm/realm-cocoa#7022]
## Goals
RealmSwift can be installed correctly under macOS environment of Github Actions.

## Expected Results
`pod install` succeeds.

## Actual Results
No error is output.
<img width="400" alt="スクリーンショット 2020-12-30 18 50 04" src="https://user-images.githubusercontent.com/2995438/103344105-f5a7cd00-4ad0-11eb-8bad-30165f7a887a.png">

## Steps for others to Reproduce
I created a reproduction project.
https://github.com/Econa77/RealmCocoapodsGitHubActions/runs/1625559150?check_suite_focus=true

## Code Sample
https://github.com/Econa77/RealmCocoapodsGitHubActions

## Version of Realm and Tooling
Realm framework version: 10.5.0
Xcode version: 12.2
iOS/OSX version: macos-10.15

Dependency manager + version: CocoaPods v1.10.0

**Comment by jsflax** [comment]
It's not clear to me why this would happen. Could you run your pod install command with the verbose flag and then paste the logs here?

**Comment by Econa77** [comment]
The log executed with the verbose option added is as follows.
Can also check the details [here](https://github.com/Econa77/RealmCocoapodsGitHubActions/runs/1625620060?check_suite_focus=true) 

<details>
<summary>log</summary><div>

```
-> Installing Realm (10.5.0)
 > Git download
 > Git download
     $ /usr/local/bin/git clone https://github.com/realm/realm-cocoa.git /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20201230-2296-2gs2yn --template= --single-branch --depth 1 --branch v10.5.0
     Cloning into '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20201230-2296-2gs2yn'...
 > Running prepare command
   $ /bin/bash -c  set -e sh build.sh cocoapods-setup
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup


/Users/runner/work/RealmCocoapodsGitHubActions/RealmCocoapodsGitHubActions/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/executable.rb:73:in `execute_command'
/Users/runner/work/RealmCocoapodsGitHubActions/RealmCocoapodsGitHubActions/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/executable.rb:27:in `block in executable'
/Users/runner/work/RealmCocoapodsGitHubActions/RealmCocoapodsGitHubActions/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/pod_source_preparer.rb:66:in `block (2 levels) in run_prepare_command'
/Users/runner/work/RealmCocoapodsGitHubActions/RealmCocoapodsGitHubActions/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/pod_source_preparer.rb:60:in `chdir'
/Users/runner/work/RealmCocoapodsGitHubActions/RealmCocoapodsGitHubActions/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/pod_source_preparer.rb:60:in `block in run_prepare_command'
/Users/runner/work/RealmCocoapodsGitHubActions/RealmCocoapodsGitHubActions/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/runner/work/RealmCocoapodsGitHubActions/RealmCocoapodsGitHubActions/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/pod_source_preparer.rb:59:in `run_prepare_command'
/Users/runner/work/RealmCocoapodsGitHubActions/RealmCocoapodsGitHubActions/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/pod_source_preparer.rb:37:in `prepare!'
/Users/runner/work/RealmCocoapodsGitHubActions/RealmCocoapodsGitHubActions/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/downloader/cache.rb:202:in `copy_and_clean'
/Users/runner/work/RealmCocoapodsGitHubActions/RealmCocoapodsGitHubActions/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/downloader/cache.rb:159:in `block (2 levels) in uncached_pod'
/Users/runner/work/RealmCocoapodsGitHubActions/RealmCocoapodsGitHubActions/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/downloader/cache.rb:157:in `each'
/Users/runner/work/RealmCocoapodsGitHubActions/RealmCocoapodsGitHubActions/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/downloader/cache.rb:157:in `block in uncached_pod'
/Users/runner/work/RealmCocoapodsGitHubActions/RealmCocoapodsGitHubActions/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/downloader/cache.rb:181:in `in_tmpdir'
/Users/runner/work/RealmCocoapodsGitHubActions/RealmCocoapodsGitHubActions/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/downloader/cache.rb:153:in `uncached_pod'
/Users/runner/work/RealmCocoapodsGitHubActions/RealmCocoapodsGitHubActions/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Users/runner/work/RealmCocoapodsGitHubActions/RealmCocoapodsGitHubActions/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/downloader.rb:42:in `download'
/Users/runner/work/RealmCocoapodsGitHubActions/RealmCocoapodsGitHubActions/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/pod_source_installer.rb:118:in `download_source'
/Users/runner/work/RealmCocoapodsGitHubActions/RealmCocoapodsGitHubActions/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/pod_source_installer.rb:69:in `install!'
/Users/runner/work/RealmCocoapodsGitHubActions/RealmCocoapodsGitHubActions/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:561:in `install_source_of_pod'
/Users/runner/work/RealmCocoapodsGitHubActions/RealmCocoapodsGitHubActions/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:512:in `block (2 levels) in install_pod_sources'
/Users/runner/work/RealmCocoapodsGitHubActions/RealmCocoapodsGitHubActions/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:86:in `titled_section'
/Users/runner/work/RealmCocoapodsGitHubActions/RealmCocoapodsGitHubActions/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:511:in `block in install_pod_sources'
/Users/runner/work/RealmCocoapodsGitHubActions/RealmCocoapodsGitHubActions/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:494:in `each'
/Users/runner/work/RealmCocoapodsGitHubActions/RealmCocoapodsGitHubActions/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:494:in `install_pod_sources'
/Users/runner/work/RealmCocoapodsGitHubActions/RealmCocoapodsGitHubActions/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:253:in `block in download_dependencies'
/Users/runner/work/RealmCocoapodsGitHubActions/RealmCocoapodsGitHubActions/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/runner/work/RealmCocoapodsGitHubActions/RealmCocoapodsGitHubActions/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:252:in `download_dependencies'
/Users/runner/work/RealmCocoapodsGitHubActions/RealmCocoapodsGitHubActions/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:161:in `install!'
/Users/runner/work/RealmCocoapodsGitHubActions/RealmCocoapodsGitHubActions/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command/install.rb:52:in `run'
/Users/runner/work/RealmCocoapodsGitHubActions/RealmCocoapodsGitHubActions/vendor/bundle/ruby/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/runner/work/RealmCocoapodsGitHubActions/RealmCocoapodsGitHubActions/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
/Users/runner/work/RealmCocoapodsGitHubActions/RealmCocoapodsGitHubActions/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
/Users/runner/work/RealmCocoapodsGitHubActions/RealmCocoapodsGitHubActions/vendor/bundle/ruby/2.6.0/bin/pod:23:in `load'
/Users/runner/work/RealmCocoapodsGitHubActions/RealmCocoapodsGitHubActions/vendor/bundle/ruby/2.6.0/bin/pod:23:in `<top (required)>'
/Users/runner/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:63:in `load'
/Users/runner/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Users/runner/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:28:in `run'
/Users/runner/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/bundler-2.2.3/lib/bundler/cli.rb:497:in `exec'
/Users/runner/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/runner/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/runner/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/Users/runner/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/bundler-2.2.3/lib/bundler/cli.rb:30:in `dispatch'
/Users/runner/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/Users/runner/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/bundler-2.2.3/lib/bundler/cli.rb:24:in `start'
/Users/runner/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/bundler-2.2.3/exe/bundle:49:in `block in <top (required)>'
/Users/runner/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/bundler-2.2.3/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
/Users/runner/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/bundler-2.2.3/exe/bundle:37:in `<top (required)>'
/Users/runner/hostedtoolcache/Ruby/2.6.6/x64/bin/bundle:23:in `load'
/Users/runner/hostedtoolcache/Ruby/2.6.6/x64/bin/bundle:23:in `<main>'
Error: Process completed with exit code 1.
```

</div></details>

**Comment by Econa77** [comment]
`sudo bundle exec pod install --allow-root` will succeed `pod install`, but the permissions below `Pods` are incorrect.
Probably, I think that some permission is insufficient and an execution error occurs while executing the following command.
`sh build.sh cocoapods-setup`

**Comment by azhydenko** [comment]
@Econa77 Did you figure out how to fix it? Could you please suggest solution?

**Comment by Econa77** [comment]
@azhydenko I haven't been able to solve this yet. Are you in the same situation?

**Comment by azhydenko** [comment]
> @azhydenko I haven't been able to solve this yet. Are you in the same situation?

Yep, just the same as yours

**Comment by Econa77** [comment]
@jsflax @azhydenko The problem has been resolved. The `DEVELOPER_DIR` specification on GitHub Actions had to be the correct path.

The changes are as follows.
https://github.com/Econa77/RealmCocoapodsGitHubActions/commit/1434a667c891fa9bd39a9cdf51072046456bf303

If the path is not set correctly, it seems that the `xcodebuild` command could not be executed and an error occurred when executing the following command.
https://github.com/realm/realm-cocoa/blob/2024cc7a45c473c75e1598d49f5a606c2caf36a5/scripts/swift-version.sh#L167
