### ISSUE TITLE
RealmStudio Invalid top array Error

### ISSUE THREAD

**Issue by emreond** [realm/realm-cocoa#7207]
## Goals

Resolve the error and see my realm database on realm studio

## Expected Results
See any data on realm studio.

## Actual Results
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/38240522/114597884-f63c2c00-9c99-11eb-9f85-2c1e17704a70.png">

## Steps for others to Reproduce

Just uninstall app, clean/build and try to open realm file with RealmStudio.

I just init Realm with `Realm()`. When I init realm, I also get bellow error which I believe related to this error.
`error: module importing failed: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/emre/Library/Application Support/Realm/rlm_lldb.py", line 37
    os.makedirs(destination, 0744)
                                ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers`

By the way, I was using both realm and realm studio without any error, I guess problems occurred after I implement
[ComposableRequest Library](https://github.com/sbertix/ComposableRequest) .

## Code Sample
```
  let realm = try Realm()
  print("Realm is located at:", realm.configuration.fileURL!)
```
## Version of Realm and Tooling
Realm framework version: 10.7.2

Realm Studio Version:  3.10.1 (3.10.1.3)

Xcode version: 12.4

iOS/OSX version: iOS 14.4 / Simulator

Dependency manager + version: Cocoapods

**Comment by pavel-ship-it** [comment]
Hi @emreond , 
Could you please try with the recent Realm Studio version?

**Comment by leemaguire** [comment]
This issue has been automatically closed because there has been no response to our request for more information from the original author. With only the information that is currently in the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need so that we can investigate further.
